### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/home/gpadmin/all_hosts.txt'

### ISSUE THREAD

**Issue by imshubhangi** [Pivotal-Data-Engineering/greenplum-workshop#1]
First step  `sudo ./01_run_as_root.sh` was executed successfully. While executing 2nd step `./02_run_as_gpadmin.sh`, I am hitting following error. 

`gpssh -f /home/gpadmin/all_hosts.txt -e 'sudo chmod 755 /usr/local'
Traceback (most recent call last):
  File "/usr/local/gpdb/bin/gpssh", line 288, in <module>
    main()
  File "/usr/local/gpdb/bin/gpssh", line 247, in main
    hostlist.parseFile(GV.opt['-f'])
  File "/usr/local/gpdb/lib/python/gppylib/util/ssh_utils.py", line 86, in parseFile
    with open(path) as fp:
IOError: [Errno 2] No such file or directory: '/home/gpadmin/all_hosts.txt'
`

**Comment by imshubhangi** [comment]
I have created file `/home/gpadmin/all_hosts.txt` containing list of hosts from greenplum db cluster, each in one line. Is this correct ?

**Comment by craig-sylvester** [comment]
Thanks for the feedback.
One of the base assumptions stated in the README is:
Greenplum Cluster has been instantiated from Pivotal's Greenplum marketplace offering on Amazon AWS. The current version of scripts has been tested with v2.2 cloud formation scripts.

The /opt/pivotal/greenplum/variables.sh script and /home/gpadmin/all_hosts.txt file are a few of the artifacts created from the AWS Greenplum marketplace offering. 

We are working on a version that will run outside of the Pivotal marketplace offerings on Azure, AWS and soon GCP.

**Comment by craig-sylvester** [comment]
Added check for the all_hosts.txt file and, if not found, advises the user to create the file and exits.
