### ISSUE TITLE
variables.sh: No such file or directory

### ISSUE THREAD

**Issue by imshubhangi** [Pivotal-Data-Engineering/greenplum-workshop#2]
First step sudo ./01_run_as_root.sh was executed successfully. While executing 2nd step ./02_run_as_gpadmin.sh, I am hitting following error.

`./00_common_functions.sh: line 8: /opt/pivotal/greenplum/variables.sh: No such file or directory
ls: cannot access /data[0-9]: No such file or directory
`

What are expected contents of /opt/pivotal/greenplum/variables.sh file ? I could not find this file in github repo.

**Comment by craig-sylvester** [comment]
The same advice given for the other issue you raised applies here.
What we are pulling from the variables.sh file is the STACK name parameter. This is only used to set the PS1 prompt and can be overridden by adding a CLUSTER_NAME environment variable to the 00_common_functions.sh script.

These set of scripts also assume that the data directories on the segment hosts are /data[0-9] (i.e., /data1, /data2, etc).
